### ISSUE TITLE
Styling issue when status bar tabs are hidden

### ISSUE THREAD

**Issue by nunocastromartins** [atom-community/linter#978]
The following styles in `linter-plus.less` do not work when hiding tabs in the status bar. Namely the "line" and "project" tabs.

```less
&:first-of-type {
  border-top-left-radius: @component-border-radius;
  border-bottom-left-radius: @component-border-radius;
}
&:last-of-type {
  margin-right: .6em;
  border-top-right-radius: @component-border-radius;
  border-bottom-right-radius: @component-border-radius;
}
```

This happens because you hide them by adding an attribute `hidden` to the DOM elements rather than removing them from the DOM. This results in the following (when both "line" and "project" tabs are hidden):

![screenshot from 2015-10-30 01-58-36](https://cloud.githubusercontent.com/assets/8314616/10836812/e1705ec2-7ea9-11e5-9fdb-06c159ff5263.png)

As you can see, the button is missing both the round corners and the right margin. The lack of a right margin looks rather bad, in my opinion.

This seems tricky to fix by only messing with the styles. I believe a good way to fix this would be to place the tabs inside a container and style the container with the outer border (with radius) and right margin.

Thank you for your amazing work so far! :smile:
